### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by tomgreco** [tus/TUSKit#131] opened 2022-05-24 13:15 UTC
When uploading large batches of files I tend to get a "EXC_BAD_ACCESS - Attempted to dereference garbage pointer" error which crashes the entire app.

Calling `TUSClient.uploadFileAt` in a loop over 200-300 files tends to cause it.

Running on an iPhone 13 Pro.

Here's the stack at the time of the crash:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/92157216/170043136-a855d572-5f34-422e-8fe9-22a9820ceb20.png">

**Comment by Acconut** [comment] 2023-03-08 11:43
Thank you for reporting this and apologies for not responding faster. Are you able to reproduce this with the current version as well?

@donnywals Do you think this is something we should investigate?

**Comment by donnywals** [comment] 2023-03-08 15:34
It's worth a shot to see if we can repro this 👍

**Comment by Acconut** [comment] 2023-06-20 11:53
Closing this issue due to a lack of information. We were not able to reproduce it. Feel free to leave a comment if you want to continue the discussion :)

**Closed by Acconut** 2023-06-20 11:53 UTC
Labels: bug
